### ISSUE TITLE
Only the server version has been tested

### ISSUE THREAD

**Issue by ranma42** [ranma42/TigerOnVBox#4]
@oboroc mentioned in https://github.com/ranma42/TigerOnVBox/issues/3#issuecomment-296456733

> I personally want to experiment with Xgrid builds over two Mac mini G4 and a dual core VM with Intel Tiger. I just wish I could use plain Tiger instead of Server, but I don't think there was a retail release for it. I do have a grey DVD with Tiger 10.4.7 for iMac late 2006 (iMac5,1), but it checks for specific hardware and refuses to work on anything that is not iMac... I wish there was a way to fake specific Mac hardware on EFI32/VBox level or at least a patch that kills the check.

I believe it should be possible to do so by mangling the DMI data.
TODO: I should check if this (and/or providing information on how to do it) is allowed by the licence.

**Comment by ranma42** [comment]
@oboroc, would you be able to provide me with a screenshot of the error?

**Comment by oboroc** [comment]
For some reasons I no longer can boot from either Tiger Server 10.4.7.dmg or the image I took of Tiger 10.4.7 for iMac late 2006.dmg in VBox VM created from your latest template.

DVD is genuine: 
![img_20170425_145055 2](https://cloud.githubusercontent.com/assets/3418650/25403337/07ce37ac-29ca-11e7-89f2-2778a6383d8e.jpg)

Here is what I get if I try to boot on Mac Mini G4, but it's most likely because DVD is for Intel only: 
![img_20170425_144518 2](https://cloud.githubusercontent.com/assets/3418650/25403387/2869cd46-29ca-11e7-8ca1-1052a68e015b.jpg)

Hardware Profiler info from Mac Mini G4: 
![img_20170425_144828 2](https://cloud.githubusercontent.com/assets/3418650/25403413/38da7068-29ca-11e7-8c8c-646b581199a8.jpg)

Update: ok somehow I resolved DVD image booting in VM. Tiger Server 10.4.7 boots reliably, but Tiger 10.4.7 for iMac late 2006 still not booting: 
![virtualbox_tiger server_25_04_2017_16_11_40](https://cloud.githubusercontent.com/assets/3418650/25405730/35e9fa42-29d2-11e7-9a12-456c7f2fb876.png)

**Comment by ranma42** [comment]
The PPC kernel seems to be loading just fine, but then it does not find the appropriate drivers for your platform (`PowerPc10,1`). It is likely that the driver bundles have been somewhat minimized to only include drivers relevant for the target hardware. I am unsure if there is much that can be done there... does the Tiger Server image boot correctly on the Mac Mini? It might be possible to use that to bootstrap the kernel.

In order to get past the `Still waiting for root device` I would suggest you to try setting the root device manually as explained in https://github.com/ranma42/TigerOnVBox/issues/2#issuecomment-297612165
The installer will probably also check for the specific hardware, therefore you might need to set the `DmiSystemProduct` through `VBoxManage`.
The `System/Installation/Packages/OSInstall.mpkg/Contents/OSInstall.dist` file on your boot media should contain a script that performs some hardware compatibility checks. You should be able to find the exact model targeted by your install software by searching for `hwbeSupportedMachines`.

Try adding to the [pre-installation configuration](https://github.com/ranma42/TigerOnVBox#create-a-new-virtual-machine) the following steps:
```
VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs 'rd=disk1sX'
VBoxManage setextradata Tiger VBoxInternal/Devices/efi/0/Config/DmiSystemProduct "YourProduct"
```
This might be sufficient to get you to the installer; hopefully once you get ther, everything just works.

**Comment by oboroc** [comment]
Hi, thank you for looking into it. I kind of guessed from the label (iMac), year (2007) and Tiger version (10.4.7 - late 2006) that my disk will check for iMac5,1 and if it's not there, refuse to boot. And the file you indicated `System/Installation/Packages/OSInstall.mpkg/Contents/OSInstall.dist` indeed has javascript code that checks for "iMac5,1". 

I ran the command as per your advise above:
```
VBoxManage setextradata Tiger VBoxInternal/Devices/efi/0/Config/DmiSystemProduct "iMac5,1"
```

I checked the dmg file I made from my DVD:
```
$ hdiutil pmap "Mac OS X Tiger 10.4.7 for iMac.dmg"
scheme:     none
block size: 512
_ ## Type_________________ Name_________________ Start___ Size____
+    Apple_HFS             whole disk                   0 10380504 

+ synthesized
```

Since my dmg doesn't seem to have multiple sub-partitions, I set it as boot disk:
```
VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs "rd=disk1"
```

After this I was able to boot from my dmg image:
![virtualbox_tiger_27_04_2017_20_57_31](https://cloud.githubusercontent.com/assets/3418650/25510418/ef0993ae-2b8d-11e7-9dbd-7fb22b35d8a7.png)

Since I only have disk 1, I had to unselect all the optional components that are on disk 2:
![virtualbox_tiger_27_04_2017_20_59_43](https://cloud.githubusercontent.com/assets/3418650/25510429/035a5ea6-2b8e-11e7-9bfd-0d617b78ecf0.png)

After this Intel Tiger 10.4.7 installed properly.

I then switched back booting to hard drive image:
```
VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs "rd=disk0"
```

Unfortunately it doesn't seem to boot for me:
![virtualbox_tiger_27_04_2017_21_17_32](https://cloud.githubusercontent.com/assets/3418650/25510574/20cd5fa0-2b8f-11e7-964c-77049ebcd46b.png)

What did I do wrong? :)

**Comment by ranma42** [comment]
I would recommend restoring the default boot args and letting the kernel search for the boot partition by uuid:
```
VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs ""
```

If that does not work, setting the hard disk as root device might help.
You have to keep into account that the hard disk is partitioned, therefore the root device that you need to configure for booting from the hard disk is going to be `disc0sX`.
if you used the default partitioning scheme, it should be `disc0s2`.
```
VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs "rd=disk0s2"
```

**Comment by oboroc** [comment]
Thank you very much!

This didn't work:

    VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs ""

However this booted me to Tiger!
    
    VBoxManage setextradata Tiger VBoxInternal2/EfiBootArgs "rd=disk0s2"

![virtualbox_tiger server_28_04_2017_08_05_42](https://cloud.githubusercontent.com/assets/3418650/25528049/b4713d76-2be9-11e7-8718-b90607c55182.png)

**Comment by oboroc** [comment]
@ranma42, please close the issue. I can't do it, since you opened it.
